name: Bump casks on schedule

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/autobump-cask.yml
  workflow_dispatch:
    inputs:
      casks:
        description: Custom list of casks to livecheck and bump if outdated
        required: false
  schedule:
    - cron: "45 */2 * * *"

permissions:
  contents: read

jobs:
  autobump:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@fc695c54c2032716dd4cedd007489c8e32fc8a5d
        with:
          core: false
          cask: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@fc695c54c2032716dd4cedd007489c8e32fc8a5d
        with:
          username: BrewTestBot

      - name: Get list of autobump casks
        id: autobump
        run: |
          autobump_list=$(brew tap-info chenrui333/homebrew-tap --json | \
            jq -c -r '.[0]["cask_tokens"] | join(" ")')
          echo "autobump_list=$autobump_list" >> "$GITHUB_OUTPUT"

      - name: Bump casks
        uses: Homebrew/actions/bump-packages@fc695c54c2032716dd4cedd007489c8e32fc8a5d
        continue-on-error: true
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          casks: ${{ github.event.inputs.casks || steps.autobump.outputs.autobump_list }}
          tap: chenrui333/tap
          fork: false
