name: Bump formulae on schedule or request

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/autobump-formula.yml
  workflow_dispatch:
    inputs:
      formulae:
        description: Custom list of formulae to livecheck and bump if outdated
        required: false
  schedule:
    - cron: "15 */2 * * *"

permissions:
  contents: read

env:
  HOMEBREW_NO_REQUIRE_TAP_TRUST: 1

jobs:
  autobump:
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@fc695c54c2032716dd4cedd007489c8e32fc8a5d
        with:
          core: false
          cask: false

      - name: Configure Git user
        uses: Homebrew/actions/git-user-config@fc695c54c2032716dd4cedd007489c8e32fc8a5d
        with:
          username: BrewTestBot

      # - name: Set up commit signing
      #   uses: Homebrew/actions/setup-commit-signing@b2da65092292aade9599608fc29415389641b3cb
      #   with:
      #     signing_key: ${{ secrets.BREWTESTBOT_GPG_SIGNING_SUBKEY }}

      - name: Get list of autobump formulae
        id: autobump
        run: |
          autobump_list=$(brew tap-info chenrui333/homebrew-tap --json | \
            jq -c -r '.[0]["formula_names"] | join(" ")')
          echo "autobump_list=$autobump_list" >> "$GITHUB_OUTPUT"

      - name: Bump formulae
        continue-on-error: true
        env:
          HOMEBREW_DEVELOPER: 1
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          HOMEBREW_TEST_BOT_AUTOBUMP: 1
          INPUT_FORMULAE: ${{ github.event.inputs.formulae || steps.autobump.outputs.autobump_list }}
        run: |
          formulae=()
          for formula in $INPUT_FORMULAE; do
            if [[ "$formula" == */*/* ]]; then
              formulae+=("$formula")
            else
              formulae+=("chenrui333/tap/$formula")
            fi
          done

          brew bump --full-name --no-fork --open-pr --formulae "${formulae[@]}"
