name: Build and Test Formulae

on:
  pull_request:
  workflow_dispatch:

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_RELOCATABLE_INSTALL_NAMES: 1
  HOMEBREW_ARM64_TESTING: 1

concurrency:
  group: "build-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  tap-syntax:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:main
    env:
      HOMEBREW_SIMULATE_MACOS_ON_LINUX: 1
    outputs:
      testing_formulae: ${{ steps.formulae-detect.outputs.testing_formulae }}
      added_formulae: ${{ steps.formulae-detect.outputs.added_formulae }}
      deleted_formulae: ${{ steps.formulae-detect.outputs.deleted_formulae }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
        with:
          core: true
          cask: false

      - run: brew test-bot --only-tap-syntax
        continue-on-error: true # Skip due to license check issues

      - run: brew test-bot --only-formulae-detect
        id: formulae-detect

  set-environment:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    needs: tap-syntax
    outputs:
      syntax-only: ${{ steps.check-labels.outputs.syntax-only }}
      linux-runner: ${{ steps.check-labels.outputs.linux-runner }}
      linux-arm64-runner: ${{ steps.check-labels.outputs.linux-arm64-runner }}
      fail-fast: ${{ steps.check-labels.outputs.fail-fast }}
      timeout-minutes: ${{ steps.check-labels.outputs.timeout-minutes }}
      container: ${{ steps.check-labels.outputs.container }}
      test-bot-formulae-args: ${{ steps.check-labels.outputs.test-bot-formulae-args }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for CI labels
        id: check-labels
        uses: actions/github-script@v7
        env:
          SCRIPTS_PATH: .github/scripts
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const path = require('path')
            const script = require(path.resolve(`${process.env.SCRIPTS_PATH}/environment.js`))
            const formula_detect = {
              testing_formulae: '${{needs.tap-syntax.outputs.testing_formulae}}',
              added_formulae: '${{needs.tap-syntax.outputs.added_formulae}}',
              deleted_formulae: '${{needs.tap-syntax.outputs.deleted_formulae}}'
            }
            try {
              await script({github, context, core}, formula_detect)
            } catch (error) {
              console.error(error);
            }

  build-formula:
    needs: set-environment
    if: github.event_name == 'pull_request' && needs.set-environment.outputs.syntax-only != 'true'
    strategy:
      matrix:
        include:
          - runner: 'macos-26'
            cleanup: true
          - runner: 'macos-15'
            cleanup: true
          - runner: 'macos-14'
            cleanup: true
          - runner: 'macos-14-x86_64'
            cleanup: true
          - runner: ${{needs.set-environment.outputs.linux-runner}}
            container: ${{fromJson(needs.set-environment.outputs.container)}}
            workdir: /github/home
            cleanup: false
            timeout: 4320
          - runner: ${{needs.set-environment.outputs.linux-arm64-runner}}
            container: ${{fromJson(needs.set-environment.outputs.container)}}
            workdir: /github/home
            cleanup: false
            timeout: 4320
      fail-fast: ${{fromJson(needs.set-environment.outputs.fail-fast)}}
    runs-on: ${{matrix.runner}}
    container: ${{matrix.container}}
    timeout-minutes: ${{ matrix.timeout || fromJson(needs.set-environment.outputs.timeout-minutes) }}
    defaults:
      run:
        shell: /bin/bash -e {0}
        working-directory: ${{matrix.workdir || github.workspace}}
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      HOMEBREW_GITHUB_API_TOKEN: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
      BOTTLES_DIR: ${{matrix.workdir || github.workspace}}/bottles
    steps:
      - name: Pre-test steps
        uses: Homebrew/actions/pre-build@master
        with:
          bottles-directory: ${{ env.BOTTLES_DIR }}
          cleanup: ${{ matrix.cleanup }}

      - name: Run brew test-bot ${{ needs.set-environment.outputs.test-bot-formulae-args }}
        id: brew-test-bot-formulae
        working-directory: ${{ env.BOTTLES_DIR }}
        run: |
          # Set Linux-specific environment variables if running on Linux
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            export HOMEBREW_PREFIX=/home/linuxbrew/.linuxbrew
            export HOMEBREW_REPOSITORY=/home/linuxbrew/.linuxbrew/Homebrew
            export HOMEBREW_CELLAR=/home/linuxbrew/.linuxbrew/Cellar
            export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
          fi
          
          brew test-bot ${{ needs.set-environment.outputs.test-bot-formulae-args }}

      - name: Post-build steps
        if: always()
        uses: Homebrew/actions/post-build@master
        with:
          runner: ${{ matrix.runner }}
          cleanup: ${{ matrix.cleanup }}
          bottles-directory: ${{ env.BOTTLES_DIR }}
          logs-directory: ${{ format('{0}/logs', env.BOTTLES_DIR) }}

  label-pr:
    needs: build-formula
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - name: Check if PR has 'in progress' label
        id: check-label
        run: |
          LABELS=$(gh pr view "${{ github.event.pull_request.number }}" --repo "${{ github.repository }}" --json labels --jq '.labels[].name')
          if echo "$LABELS" | grep -q "^in progress$"; then
            echo "skip_label=true" >> "$GITHUB_ENV"
          else
            echo "skip_label=false" >> "$GITHUB_ENV"
          fi
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}

      - name: Label the PR with 'pr-pull'
        if: env.skip_label == 'false'
        run: gh pr edit "${{ github.event.pull_request.number }}" --add-label 'pr-pull' --repo "${{ github.repository }}"
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
