name: Process Compose Preflight

on:
  push:
    branches:
      - process-compose-preflight
    paths:
      - ".github/workflows/process-compose-preflight.yml"
      - "Formula/p/process-compose.rb"
  workflow_dispatch:

env:
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_GITHUB_ACTIONS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  HOMEBREW_RELOCATABLE_INSTALL_NAMES: 1
  HOMEBREW_ARM64_TESTING: 1

jobs:
  preflight:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - macos-15
          - ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@83bb8c72e8bbeb6ffc77f827f06a9720a7779b7e
        with:
          core: true
          cask: false

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install from source
        run: brew install --build-from-source chenrui333/tap/process-compose

      - name: Run formula test
        run: brew test chenrui333/tap/process-compose

      - name: Run linkage test
        run: brew linkage --test chenrui333/tap/process-compose

      - name: Run audit
        run: brew audit --new chenrui333/tap/process-compose

      - name: Run style
        run: brew style Formula/p/process-compose.rb
